module.exports = [
  { regex: /^\/\*([^*]|\*(?!\/))*\*\/$/, type: 'area_comment' },
  { regex: /^\/\*([^*]|\*(?!\/))*\*?$/, type: 'area_comment_continue' },
  { regex: /^\/\/[^\n]*$/, type: 'line_comment' },
  { regex: /^"([^"\n]|\\")*"?$/, type: 'quote' },
  { regex: /^'(\\?[^'\n]|\\')'?$/, type: 'char' },
  { regex: /^'[^']*$/, type: 'char_continue' },
  { regex: /^#(\S*)$/, type: 'directive' },
  { regex: /^\($/, type: 'open_paren' },
  { regex: /^\)$/, type: 'close_paren' },
  { regex: /^\[$/, type: 'open_square' },
  { regex: /^\]$/, type: 'close_square' },
  { regex: /^{$/, type: 'open_curly' },
  { regex: /^}$/, type: 'close_curly' },
  { regex: /^([-<>~!%^&*\/+=?|.,:;]|->|<<|>>|\*\*|\|\||&&|--|\+\+|[-+*|&%\/=]=)$/,
      type: 'operator' },
  { regex: /^([_A-Za-z]\w*)$/, type: 'identifier' },
  { regex: /^[0-9]*\.?[0-9]+([eE][-+]?[0-9]+)?$/, type: 'number' },
  { regex: /^(\s+)$/, type: 'whitespace' },
  { regex: /^\\\n?$/, type: 'line_continue' }
]
